### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by prahjister** [nikolaseu/neuvision#24]
Is is possible to provide a Windows binary and necessary libraries. I would like to try this project but don't have the necessary skills to compile

**Comment by nikolaseu** [comment]
What are you interested in? The scanner or camera calibration? Which kind of camera/s are you using?

I have many things planned but sadly I don't have as much free time as I would like. Right now this is like a framework to help people (only me?) test & develop computer vision/calibration/scanning projects, you need to know how to build it yourself. It's not really finished for end users (one of the TODOs 😞)
