### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by kevz93** [nikolaseu/neuvision#29]
Could you explain more about this config file that is missing as mentioned in the README ?

**Comment by nikolaseu** [comment]
Hi, I would be more than happy to help but I started refactoring some things and it's not finished yet, so I think right now the scanner application is not working. If you're willing to help, don't hesitate to ask me.

Basically the file (`Z3DScanner.ini`) should look like this (just as an example, for stereo with binary patterns and simulated cameras):
```ini
[StructuredLightSystem]
Type=Z3D::ZStereoSLSPlugin
Mode=DualCamera
Cameras/Left/Type=Z3D::ZSimulatedCameraPlugin
Cameras/Left/Name=Left
Cameras/Left/Folder=../sample/left
Cameras/Right/Type=Z3D::ZSimulatedCameraPlugin
Cameras/Right/Name=Right
Cameras/Right/Folder=../sample/right
StereoCalibration/Type=Pinhole
StereoCalibration/ConfigFile=/Users/nikolaseu/Projects/neuvision/bin/calib/20180110181159.multicameracalib.yml
PatternProjection/Type=Z3D::ZBinaryPatternProjectionPlugin
```

The sub-options depend on the plugins being used, and sadly you'll need to check the code to know what's required. And also to check what's wrong when it's not working 😄
I just don't have enough free time

**Comment by kevz93** [comment]
Im happy to help! I'll wait till you're done with the refactor. Meanwhile Ill see if there is anything I can do.
One thing I'd to Implement is basic image processing for surfaces.
