### ISSUE TITLE
request

### ISSUE THREAD

**Issue by nesquik011** [nikolaseu/neuvision#32]
i request axis movement something like this  not 5 axis movement just 2 or 3 

https://www.youtube.com/watch?v=7N1DY561ArQ

**Comment by nikolaseu** [comment]
Sorry, but I don't even have the hardware to test it.

**Comment by nesquik011** [comment]
what hardware do you need ? just drivers and steppers and Arduino or raspberry pi right ? or add axis movement and I will find someone to compile it and try to test
