### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by dentx22** [nikolaseu/neuvision#47]
Selecting Windows SDK version 10.0.18362.0 to target Windows 6.1.7601.
This is a release build (CMAKE_BUILD_TYPE=Release)
CMake Error at lib/zcore/CMakeLists.txt:31 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

CMake Error at lib/zgui/CMakeLists.txt:37 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

CMake Error at lib/zcameraacquisition/CMakeLists.txt:38 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

i have problems with cmake

**Comment by nikolaseu** [comment]
Maybe git is not on the path so the version cannot be obtained? Can you check that you get something like [this](https://ci.appveyor.com/project/nikolaseu/neuvision/branch/master?fullLog=true#L251) in your log?

**Comment by dentx22** [comment]
tnks all work


I hope you can mine david scanner software

thank you
