### ISSUE TITLE
configuration file

### ISSUE THREAD

**Issue by dentx22** [nikolaseu/neuvision#49]
all work ok
now i need the ini file
with an opencv camera
and a projector

please authorize me
where am i wrong?

[StructuredLightSystem]
Type=Z3D::ZBinaryPatternProjection
Mode=singlecamera
Cameras/Type=Z3D::zopencvvideocapture
cameracalibration/ConfigFile=..\tmp\cameracalibration\20200201120920_ZOpenCV-94336528.ini
PatternProjection/Type=Z3D::ZBinaryPatternProjectionPlugin

**Comment by nikolaseu** [comment]
It doesn't work with only one camera, I never had time to finish it.
The config should be something like this (replace cameras obviously):
```
[StructuredLightSystem]
Type=Z3D::ZStereoSLSPlugin
Mode=DualCamera
Cameras/Left/Type=Z3D::ZSimulatedCameraPlugin
Cameras/Left/Name=Left
Cameras/Left/Folder=<FOLDER WITH LEFT CAMERA IMAGES>
Cameras/Right/Type=Z3D::ZSimulatedCameraPlugin
Cameras/Right/Name=Right
Cameras/Right/Folder=<FOLDER WITH RIGHT CAMERA IMAGES>
StereoCalibration/Type=Pinhole
StereoCalibration/ConfigFile=<FILE FROM MULTI CAMERA CALIBRATION APP .multicameracalib.yml>
PatternProjection/Type=Z3D::ZBinaryPatternProjectionPlugin
```

**Comment by nesquik011** [comment]
@dentx22 what cameras are you using ? may you provide link and model , and projector resolution ?

**Comment by Genn4dental** [comment]
acer 1280 /800
1,920×1,200 (2.3 MP) Y800 @ 54 fps
dmk23ux236

**Comment by nesquik011** [comment]
@Genn4dental   thank you , the project is native 1280*800 right ? 

can you provide the ini file of this camera

**Comment by Genn4dental** [comment]
yes windows

**Comment by nesquik011** [comment]
> yes windows

great about ini ?
