### ISSUE TITLE
 not ready for single camera ?

### ISSUE THREAD

**Issue by dentx22** [nikolaseu/neuvision#51]
![Cattura](https://user-images.githubusercontent.com/50907901/75157898-562de700-5715-11ea-94bb-853764cbde76.JPG)

ini one camera
[StructuredLightSystem]
Type=Z3D::ZStereoSLSPlugin
Mode=Projector+Camera
Camera/Type=Z3D::ZOpenCVVideoCapturePlugin
StereoCalibration/Type=Pinhole
StereoCalibration/ConfigFile=tmp/multicameracalibration/20200221200723/20200222112816.multicameracalib.yml
PatternProjection/Type=Z3D::ZBinaryPatternProjectionPlugin

or something wrong?

![Cattur1a](https://user-images.githubusercontent.com/50907901/75158184-e10ee180-5715-11ea-8dca-59d388ea01d9.JPG)

ini two camera
[StructuredLightSystem]
Type=Z3D::ZStereoSLSPlugin
Mode=DualCamera
Cameras/Left/Type=Z3D::ZOpenCVVideoCapturePlugin
Cameras/Left/Name=Left
Cameras/Left/Folder=../sample/left
Cameras/Right/Type=Z3D::ZOpenCVVideoCapturePlugin
Cameras/Right/Name=Right
Cameras/Right/Folder=../sample/right
StereoCalibration/Type=Pinhole
StereoCalibration/ConfigFile=tmp/multicameracalibration/20200221200723/20200222112816.multicameracalib.yml
PatternProjection/Type=Z3D::ZBinaryPatternProjectionPlugin

**Comment by nikolaseu** [comment]
Yeah, it's not supported yet. Contributions welcome!
